global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['node-app:3000']
  - job_name: 'prod-app'
    scheme: https
    static_configs:
      - targets: ['week-25.100xdevs.com']